# Generated by Django 4.1.7 on 2023-05-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cherry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
